define({ entries : {
    "dabek_timeline-based_2017": {
        "abstract": "Electronic Health Records (EHRs) contain a significant amount of longitudinal information about a patient including pre-existing conditions, earlier diagnosis, previous treatments, active medications, base-line measurements for different clinical results, and much more. Unfortunately, data integration within an EHR and across different EHRs continue to be a limiting factor that threatens patient safety and the efficiency of healthcare providers. The disparate nature of the clinical data even within a single EHR often results in clinicians having to access and review a number of reports, modules, and tabs to access different data elements and clinical results. Due to the fragmented nature of EHR interfaces and the number of interactions that are needed to access clinical data, clinicians often spend a considerable part of their time going through the EHR of a patient in order to get a comprehensive overview and to be able to provide quality care. Data visualization and the integration of analytic models within graphical interfaces present a unique opportunity to effectively combine multiple clinical data sources and reduce the cognitive burden that disparate reports often have for end-users. With the ability of visualization techniques to summarize different data elements, we present a timeline-based framework to effectively aggregate and summarize the disparate clinical data of a patient enclosed within an EHR. The interface combines a set of visualization techniques with machine learning summarization approaches to optimize the process of understanding a patient's history through views that allow for easily skimming and jumping through time, filters for limiting the amount of information shown, and a hierarchy of summaries that provide an interface to view and compare different time frames.",
        "author": "Dabek, Filip and Jimenez, Elizabeth and Caban, Jesus J.",
        "booktitle": "2017 {IEEE} {Workshop} on {Visual} {Analytics} in {Healthcare} ({VAHC})",
        "doi": "10.1109/VAHC.2017.8387501",
        "file": "IEEE Xplore Abstract Record:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\BBMV7VKV\\\\8387501.html:text/html;IEEE Xplore Full Text PDF:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\MTICNT8H\\\\Dabek et al. - 2017 - A timeline-based framework for aggregating and sum.pdf:application/pdf",
        "keywords": "Aggregates, Data visualization, Electronic medical records, History, Limiting, Medical diagnostic imaging, Navigation",
        "month": "oct,",
        "pages": "55--61",
        "title": "A timeline-based framework for aggregating and summarizing electronic health records",
        "type": "inproceedings",
        "year": "2017"
    },
    "klemm_3d_2016": {
        "abstract": "Epidemiological studies comprise heterogeneous data about a subject group to define disease-specific risk factors. These data contain information (features) about a subject's lifestyle, medical status as well as medical image data. Statistical regression analysis is used to evaluate these features and to identify feature combinations indicating a disease (the target feature). We propose an analysis approach of epidemiological data sets by incorporating all features in an exhaustive regression-based analysis. This approach combines all independent features w.r.t. a target feature. It provides a visualization that reveals insights into the data by highlighting relationships. The 3D Regression Heat Map, a novel 3D visual encoding, acts as an overview of the whole data set. It shows all combinations of two to three independent features with a specific target disease. Slicing through the 3D Regression Heat Map allows for the detailed analysis of the underlying relationships. Expert knowledge about disease-specific hypotheses can be included into the analysis by adjusting the regression model formulas. Furthermore, the influences of features can be assessed using a difference view comparing different calculation results. We applied our 3D Regression Heat Map method to a hepatic steatosis data set to reproduce results from a data mining-driven analysis. A qualitative analysis was conducted on a breast density data set. We were able to derive new hypotheses about relations between breast density and breast lesions with breast cancer. With the 3D Regression Heat Map, we present a visual overview of epidemiological data that allows for the first time an interactive regression-based analysis of large feature sets with respect to a disease.",
        "author": "Klemm, Paul and Lawonn, Kai and Gla\u00dfer, Sylvia and Niemann, Uli and Hegenscheid, Katrin and V\u00f6lzke, Henry and Preim, Bernhard",
        "doi": "10.1109/TVCG.2015.2468291",
        "file": "IEEE Xplore Abstract Record:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\H6VY8MI3\\\\7194847.html:text/html;IEEE Xplore Full Text PDF:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\UJQQC6KT\\\\Klemm et al. - 2016 - 3D Regression Heat Map Analysis of Population Stud.pdf:application/pdf",
        "issn": "1941-0506",
        "journal": "IEEE Transactions on Visualization and Computer Graphics",
        "keywords": "Data visualization, Breast Cancer, Correlation, Diseases, Epidemiology, Feature extraction, Heat Map, Heating, Hepatic Steatonis, Hepatic Steatosis, Interactive Visual Analysis, Measurement, Regression Analysis, Three-dimensional displays",
        "month": "jan,",
        "note": "Conference Name: IEEE Transactions on Visualization and Computer Graphics",
        "number": "1",
        "pages": "81--90",
        "title": "{3D} {Regression} {Heat} {Map} {Analysis} of {Population} {Study} {Data}",
        "type": "article",
        "volume": "22",
        "year": "2016"
    },
    "linhares_clinicalpath_2022": {
        "abstract": "Physicians work at a very tight schedule and need decision-making support tools to help on improving and doing their work in a timely and dependable manner. Examining piles of sheets with test results and using systems with little visualization support to provide diagnostics is daunting, but that is still the usual way for the physicians' daily procedure, especially in developing countries. Electronic Health Records systems have been designed to keep the patients' history and reduce the time spent analyzing the patient's data. However, better tools to support decision-making are still needed. In this paper, we propose ClinicalPath, a visualization tool for users to track a patient's clinical path through a series of tests and data, which can aid in treatments and diagnoses. Our proposal is focused on patient's data analysis, presenting the test results and clinical history longitudinally. Both the visualization design and the system functionality were developed in close collaboration with experts in the medical domain to ensure a right fit of the technical solutions and the real needs of the professionals. We validated the proposed visualization based on case studies and user assessments through tasks based on the physician's daily activities. Our results show that our proposed system improves the physicians' experience in decision-making tasks, made with more confidence and better usage of the physicians' time, allowing them to take other needed care for the patients.",
        "author": "Linhares, Claudio D. G. and Lima, Daniel M. and Ponciano, Jean R. and Olivatto, Mauro M. and Gutierrez, Marco A. and Poco, Jorge and Traina, Caetano and Traina, Agma Juci Machado",
        "doi": "10.1109/TVCG.2022.3175626",
        "file": "IEEE Xplore Abstract Record:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\3JN8PS6G\\\\9779066.html:text/html;IEEE Xplore Full Text PDF:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\CFX3CNHW\\\\Linhares et al. - 2022 - ClinicalPath a Visualization tool to Improve the .pdf:application/pdf",
        "issn": "1941-0506",
        "journal": "IEEE Transactions on Visualization and Computer Graphics",
        "keywords": "Data visualization, History, Medical diagnostic imaging, Decision making, Electronic Health Records, Human-Computer Interaction, Information Visualization, Interactive Visualizations, Medical services, Task analysis, Visualization",
        "note": "Conference Name: IEEE Transactions on Visualization and Computer Graphics",
        "pages": "1--1",
        "shorttitle": "{ClinicalPath}",
        "title": "{ClinicalPath}: a {Visualization} tool to {Improve} the {Evaluation} of {Electronic} {Health} {Records} in {Clinical} {Decision}-{Making}",
        "type": "article",
        "year": "2022"
    },
    "liu_interactive_2023": {
        "abstract": "Similar patient retrieval has become increasingly important with the explosive growth of electronic health records (EHRs). A similar patient cohort identified from all patients can provide data-driven insights for personalized healthcare. However, the high dimensionality and heterogeneity of EHRs increase the difficulty of measuring patient similarity. How to accurately and efficiently retrieve similar patients from a large number of EHRs remains challenging. In this paper, we propose a novel similar patient retrieval method based on interactive patient labeling and automatic model updating. Combined with the knowledge and experience of physicians, it can be adaptively modified for different patients and diseases. We also develop a visual analytics system to assist patient labeling through pairwise comparisons and support outcome analysis of similar patients. The case studies on two real-world datasets in collaboration with physicians demonstrate the effectiveness and usefulness of our method.",
        "author": "Liu, Huan and Dai, Haoran and Chen, Juntian and Xu, Jin and Tao, Yubo and Lin, Hai",
        "doi": "10.1007/s12650-022-00898-9",
        "file": "Full Text PDF:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\M232CDSW\\\\Liu et al. - 2023 - Interactive similar patient retrieval for visual s.pdf:application/pdf",
        "issn": "1875-8975",
        "journal": "Journal of Visualization",
        "keywords": "Personalized medicine, Similar patient retrieval, Visual interactive labeling",
        "language": "en",
        "month": "jun,",
        "number": "3",
        "pages": "577--592",
        "title": "Interactive similar patient retrieval for visual summary of patient outcomes",
        "type": "article",
        "url": "https://doi.org/10.1007/s12650-022-00898-9",
        "urldate": "2023-05-15",
        "volume": "26",
        "year": "2023"
    },
    "liu_visualization_2021": {
        "abstract": "Visualization, as a vibrant field for researchers, practitioners, and higher educational institutions, is growing and evolving very rapidly. Tremendous progress has been made since 1987, the year often cited as the beginning of data visualization as a distinct field. As such, the number of visualization resources and the demand for those resources are increasing at a very fast pace. We present a collection of open visualization resources for all those with an interest in interactive data visualization and visual analytics. Because the number of resources is so large, we focus on collections of resources, of which there are already very many ranging from literature collections to collections of practitioner resources. We develop a novel classification of visualization resource collections based on the resource type, e.g. literature-based, web-based, etc. The result is a helpful overview and details-on-demand of many useful resources. The collection offers a valuable jump-start for those seeking out data visualization resources from all backgrounds spanning from beginners such as students to teachers, practitioners, and researchers wishing to create their own advanced or novel visual designs.",
        "author": "Liu, Xiaoxiao and Alharbi, Mohammad and Best, Joe and Chen, Jian and Diehl, Alexandra and Firat, Elif and Rees, Dylan and Wang, Qiru and Laramee, Robert S",
        "booktitle": "2021 25th {International} {Conference} {Information} {Visualisation} ({IV})",
        "doi": "10.1109/IV53921.2021.00034",
        "file": "IEEE Xplore Abstract Record:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\S96HJQ2W\\\\9582718.html:text/html;IEEE Xplore Full Text PDF:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\XPL4UTGN\\\\Liu et al. - 2021 - Visualization Resources A Starting Point.pdf:application/pdf",
        "keywords": "Data visualization, Distance measurement, Software, surveys, Tools, Videos, Visual analytics, visualization resources",
        "month": "jul,",
        "note": "ISSN: 2375-0138",
        "pages": "160--169",
        "shorttitle": "Visualization {Resources}",
        "title": "Visualization {Resources}: {A} {Starting} {Point}",
        "type": "inproceedings",
        "year": "2021"
    },
    "mcnabb_how_2019": {
        "abstract": "This paper attempts to explain the mechanics of writing a survey paper in data visualization or visual analytics. It serves as a useful starting point for those who have never written a survey paper or have very little experience. A literature review or survey paper is often considered the starting point of a PhD candidate's scientific degree. However, there are no dedicated papers that focus on guidelines for the planning or writing of a survey paper or literature review in visualization or visual analytics. We provide guidelines and our recommendations for a foundational structure on which to build a survey paper, whilst also considering intermediate goals, and offer helpful advice to improve the survey process and literature analysis. The result is a useful starting point for those wishing to write a survey paper or state-of-the-art (STAR) review in visualization or visual analytics. The guidelines and recommendations we make can also be generalized to other areas of computing and science. An abstract is a required feature of a survey paper and should identity the topic of the literature review. A good abstract addresses why the given topic is interesting and why it is helpful. A good abstract features the following elements: (1) topic introduction, (2) the motivation, (3) the goal of the review, and the benefits the review provides to the reader. A good literature survey offers a helpful classification of the literature, mature areas of research, and open, unsolved problems in visualization or visual analytics.",
        "author": "McNabb, Liam and Laramee, Robert S.",
        "doi": "10.2312/eged.20191026",
        "file": "Full Text PDF:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\9S53UBIU\\\\McNabb and Laramee - 2019 - How to Write a Visualization Survey Paper A Start.pdf:application/pdf",
        "issn": "1017-4656",
        "language": "en",
        "note": "Accepted: 2019-05-05T17:46:20Z Publisher: The Eurographics Association",
        "shorttitle": "How to {Write} a {Visualization} {Survey} {Paper}",
        "title": "How to {Write} a {Visualization} {Survey} {Paper}: {A} {Starting} {Point}",
        "type": "article",
        "url": "https://diglib.eg.org:443/xmlui/handle/10.2312/eged20191026",
        "urldate": "2023-05-15",
        "year": "2019"
    },
    "sopan_community_2012": {
        "abstract": "Trillions of dollars are spent each year on health care. The U.S. Department of Health and Human Services keeps track of a variety of health care indicators across the country, resulting in a large geospatially multivariate data set. Current visualization tools for such data sets make it difficult to make multivariate comparisons and show the geographic distribution of the selected variables at the same time. Community Health Map is a web application that enables users to visualize health care data in multivariate space as well as geospatially. It is designed to aid exploration of this huge data repository and deliver deep insights for policy makers, journalists, consumer groups, and academic researchers. Users can visualize the geospatial distribution of a given variable on an interactive map, and compare two or more variables using charts and tables. By employing dynamic query filters, visualizations can be narrowed down to specific ranges and regions. Our presentation to policy makers and pilot usability evaluation suggest that the Community Health Map provides a comprehensible and powerful interface for policy makers to visualize health care quality, public health outcomes, and access to care in an effort to help them to make informed decisions about improving health care.",
        "author": "Sopan, Awalin and Noh, Angela Song-Ie and Karol, Sohit and Rosenfeld, Paul and Lee, Ginnah and Shneiderman, Ben",
        "doi": "10.1016/j.giq.2011.10.002",
        "file": "ScienceDirect Full Text PDF:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\QQ3NAW6A\\\\Sopan et al. - 2012 - Community Health Map A geospatial and multivariat.pdf:application/pdf;ScienceDirect Snapshot:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\33CQU7CK\\\\S0740624X12000159.html:text/html",
        "issn": "0740-624X",
        "journal": "Government Information Quarterly",
        "keywords": "Geospatial multivariate visualization, Graphical user interface, Healthcare data, Information visualization",
        "language": "en",
        "month": "apr,",
        "number": "2",
        "pages": "223--234",
        "shorttitle": "Community {Health} {Map}",
        "title": "Community {Health} {Map}: {A} geospatial and multivariate data visualization tool for public health datasets",
        "type": "article",
        "url": "https://www.sciencedirect.com/science/article/pii/S0740624X12000159",
        "urldate": "2023-05-15",
        "volume": "29",
        "year": "2012"
    },
    "sultanum_chartwalk_2023": {
        "abstract": "Before seeing a patient for the first time, healthcare workers will typically conduct a comprehensive clinical chart review of the patient's electronic health record (EHR). Within the diverse documentation pieces included there, text notes are among the most important and thoroughly perused segments for this task; and yet they are among the least supported medium in terms of content navigation and overview. In this work, we delve deeper into the task of clinical chart review from a data visualization perspective and propose a hybrid graphics+text approach via ChartWalk, an interactive tool to support the review of text notes in EHRs. We report on our iterative design process grounded in input provided by a diverse range of healthcare professionals, with steps including: (a) initial requirements distilled from interviews and the literature, (b) an interim evaluation to validate design decisions, and (c) a task-based qualitative evaluation of our final design. We contribute lessons learned to better support the design of tools not only for clinical chart reviews but also other healthcare-related tasks around medical text analysis.",
        "author": "Sultanum, Nicole and Naeem, Farooq and Brudno, Michael and Chevalier, Fanny",
        "doi": "10.1109/TVCG.2022.3209444",
        "file": "IEEE Xplore Abstract Record:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\5S4VQS2Q\\\\9904479.html:text/html;IEEE Xplore Full Text PDF:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\AXGJSEJR\\\\Sultanum et al. - 2023 - ChartWalk Navigating large collections of text no.pdf:application/pdf",
        "issn": "1941-0506",
        "journal": "IEEE Transactions on Visualization and Computer Graphics",
        "keywords": "Data visualization, Navigation, Medical services, Task analysis, Visualization, Clinical Overview, Close+Distant Reading, Electronic Health Record (EHR), Iterative methods, Medicine, Natural language processing, Text Visualization",
        "month": "jan,",
        "note": "Conference Name: IEEE Transactions on Visualization and Computer Graphics",
        "number": "1",
        "pages": "1244--1254",
        "shorttitle": "{ChartWalk}",
        "title": "{ChartWalk}: {Navigating} large collections of text notes in electronic health records for clinical chart review",
        "type": "article",
        "volume": "29",
        "year": "2023"
    },
    "wang_ehr_2022": {
        "abstract": "Since the inception of electronic health records (EHR) and population health records (PopHR), the volume of archived digital health records is growing rapidly. Large volumes of heterogeneous health records require advanced visualization and visual analytics systems to uncover valuable insight buried in complex databases. As a vibrant sub-field of information visualization and visual analytics, many interactive EHR and PopHR visualization (EHR Vis) systems have been proposed, developed, and evaluated by clinicians to support effective clinical analysis and decision making. We present the state-of-the-art (STAR) of EHR Vis literature and open access healthcare data sources and provide an up-to-date overview on this important topic. We identify trends and challenges in the field, introduce novel literature and data classifications, and incorporate a popular medical terminology standard called the Unified Medical Language System (UMLS). We provide a curated list of electronic and population healthcare data sources and open access datasets as a resource for potential researchers, in order to address one of the main challenges in this field. We classify the literature based on multidisciplinary research themes stemming from reoccurring topics. The survey provides a valuable overview of EHR Vis revealing both mature areas and potential future multidisciplinary research directions.",
        "author": "Wang, Q. and Laramee, R.s.",
        "doi": "10.1111/cgf.14424",
        "file": "Full Text PDF:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\YZQE2KAF\\\\Wang and Laramee - 2022 - EHR STAR The State-Of-the-Art in Interactive EHR .pdf:application/pdf;Snapshot:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\QJQ3HJKX\\\\cgf.html:text/html",
        "issn": "1467-8659",
        "journal": "Computer Graphics Forum",
        "keywords": "electronic health records, information visualization, interaction, interaction techniques, visual analytics, visualization",
        "language": "en",
        "note": "\\_eprint: https://onlinelibrary.wiley.com/doi/pdf/10.1111/cgf.14424",
        "number": "1",
        "pages": "69--105",
        "shorttitle": "{EHR} {STAR}",
        "title": "{EHR} {STAR}: {The} {State}-{Of}-the-{Art} in {Interactive} {EHR} {Visualization}",
        "type": "article",
        "url": "https://onlinelibrary.wiley.com/doi/abs/10.1111/cgf.14424",
        "urldate": "2023-05-15",
        "volume": "41",
        "year": "2022"
    },
    "wang_lettervis_2021": {
        "abstract": "The number of electronic health records (EHRs) collected by healthcare providers is growing at an unprecedented pace. Clinicians often compose detailed clinic letters to record as much essential information during consultations as they can. This increases the workload of analyzing these letters, performing individual and collective analysis, and clinical decision making. This paper presents a novel visualization tool, LetterVis, to support the analysis of clinic letters through advanced interactive visual designs and queries. We describe a letter-space that facilities the visual exploration of content and patterns inside a letter. Letters are processed using natural language processing techniques and explored in multiple linked interactive views providing different levels of abstraction. The tool includes customized visual designs and views for visualizing antiepileptic drugs (AEDs). We provide a range of filtering and selection options to assist pattern finding and outlier detection. We demonstrate LetterVis with three case studies using anonymized clinic letters, revealing insight that is normally either time-consuming or impossible to observe. Domain expert partners from EHR analysis review the software and are involved in every phase from the initial design to evaluation.",
        "author": "Wang, Qiru and Laramee, Robert S. and Lacey, Arron and Pickrell, William Owen",
        "doi": "10.1007/s00371-021-02171-w",
        "file": "Full Text PDF:C\\:\\\\Users\\\\Dharanija Bantu\\\\Zotero\\\\storage\\\\D2ULBX39\\\\Wang et al. - 2021 - LetterVis a letter-space view of clinic letters.pdf:application/pdf",
        "issn": "1432-2315",
        "journal": "The Visual Computer",
        "keywords": "Electronic Health Records, Information Visualization, Visual Analytics",
        "language": "en",
        "month": "sep,",
        "number": "9",
        "pages": "2643--2656",
        "shorttitle": "{LetterVis}",
        "title": "{LetterVis}: a letter-space view of clinic letters",
        "type": "article",
        "url": "https://doi.org/10.1007/s00371-021-02171-w",
        "urldate": "2023-05-15",
        "volume": "37",
        "year": "2021"
    }
}});